### ISSUE TITLE
setup.py wrong package_data

### ISSUE THREAD

**Issue by ifokeev** [singer-io/tap-github#10]
I see that `setup.py` have wrong `package_data` and that's why I can't run the script now. 
I'm not a python guy is this a bug or feature?

**Comment by nick-mccoy** [comment]
Hi @ifokeev, yesterday we released a pretty big update to this tap, and this change was included.  

Make sure you check out the updated README before running the tap -- some of the streams have changed, and the steps to run the tap are different.

**Comment by nick-mccoy** [comment]
This should be fixed in the new version, so I am closing the issue.
