### ISSUE TITLE
feature request: repository as a parameter

### ISSUE THREAD

**Issue by ifokeev** [singer-io/tap-github#12]
Guys, please, add the cli-parameter --repo to achieve opportunity calling script for any number of repositories not one per config

**Comment by nick-mccoy** [comment]
Hey @ifokeev, this is an interesting idea.  Instead of making it a cli-parameter, we would probably make the config file 'repository' value a list instead instead of a single string.  We will discuss the possibility of doing this, and I will update you when we've made a decision.

**Comment by nick-mccoy** [comment]
Hey @ifokeev, I spoke with my team and we think the best solution would be to make the repository value a list of repos.  [Tap-gitlab](https://github.com/singer-io/tap-gitlab) does something very similar with its 'projects' field.  

You are free to submit a pull request with the changes, but we probably won't choose to implement this ourselves.  I'm going to close this issue.
