### ISSUE TITLE
Better support for multiple repositories

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-github#19]
The tap as it currently stands is a little awkward for scanning multiple repositories. A couple of things that would help:

 * Allow an array of values to be passed to the repository config option (or allow a separate "repositories" option that can be an array)
 * Including a repository reference on each row of the data tables, so that, say, commits or reviews from a single repository can be identified.

**Comment by nick-mccoy** [comment]
Hi @sminnee -- This is something we plan on implementing in the future, but you are free to submit a PR with the changes if you'd like to expedite the process.  Otherwise, I'll update this issue once the changes have been made.

**Comment by alisaraa** [comment]
hey all,
I'd just like to second this request. Specifically, my concern is not how easy it is to make an integration (I don't care if there are box selections or if I have to type in the names of the repos), but rather how having multiple schemas of data would cause overhead in integrating them.
