### ISSUE TITLE
Incompatible with target-stitch state data

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-github#21]
I'm crossposting https://github.com/singer-io/target-stitch/issues/48 because it's not clear to me which project needs to be corrected here.

Stitch produces output along this lines, which seems to mean that that I won't get assignees state data if I limit it to the last row.

```
{"table_name": "assignees", ...}
{"table_name": "collaborators", ...}
{"table_name": "stargazers", ...}
{"table_name": "issues", ...}
```

tap-github seems to expect a state file of the following form:

```
{"commits": "<datetime>", "issues": "<datetime>", ...}
```

What is the best way of resolving this?

**Comment by sminnee** [comment]
Related to this may be that the STATE messages that the tap outputs don't have any value.

```
> tap-github -c github-config.json -p github-properties.json | grep STATE

{"type": "STATE", "value": {}}
{"type": "STATE", "value": {}}
{"type": "STATE", "value": {}}
```

**Comment by nick-mccoy** [comment]
Hi @sminnee -- yes, tap-github only supports full table replication right now, so there will be no state data written/read by the tap.  We do plan on implementing this in the future, but for now it will stay full-table replication only

**Comment by nick-mccoy** [comment]
Incremental replication has been added, so I'm closing this!
