### ISSUE TITLE
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}

### ISSUE THREAD

**Issue by alisaraa** [singer-io/tap-github#27]
Hey all,
Our Github integration has gotten that error message in June. It worked before that, can you advise?
Thanks,
Alisa

**Comment by briansloane** [comment]
@alisaraa Glad to see this was resolved. Can you share what the fix was?

**Comment by NoLookForcePush** [comment]
One reason for this, is if you are using the Personal Access Token in an org that has SAML. If so, you will see this error until you [authorize your PAT with SAML](https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on)
