### ISSUE TITLE
Import change events

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-github#41]
It doesn't appear as though there is any data about issue status changes are coming through. This makes it very difficult to report on the number of issues open / closed over time.

I believe that this would involve adding the "event" data to the schema, but there may be multiple ways to approach this.

Is this something that could be added?

**Comment by sminnee** [comment]
Apologies, I was too hasty and neglected to see that closed_at should be available too, which would suffice for my reporting needs.

I'm not sure if https://developer.github.com/v3/issues/events/ would be useful for other people, but perhaps this issue can be closed.

**Comment by KAllan357** [comment]
What I can do is close this and add another issue for the Events stream.
