### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by AlexanderMann** [singer-io/tap-github#50]
# Motivation

code-version: 1.3.3

Getting the following error:

```
Traceback (most recent call last):
  File "/code/venv--tap-github/bin/tap-github", line 11, in <module>
    load_entry_point('tap-github==1.3.3', 'console_scripts', 'tap-github')()
  File "/code/venv--tap-github/lib/python3.7/site-packages/singer/utils.py", line 225, in wrapped
    return fnc(*args, **kwargs)
  File "/code/venv--tap-github/lib/python3.7/site-packages/tap_github.py", line 515, in main
    do_sync(args.config, args.state, catalog)
  File "/code/venv--tap-github/lib/python3.7/site-packages/tap_github.py", line 488, in do_sync
    state = sync_func(stream_schema, repo, state, mdata)
  File "/code/venv--tap-github/lib/python3.7/site-packages/tap_github.py", line 376, in get_all_comments
    comment['_sdc_repository'] = repo_path
TypeError: 'str' object does not support item assignment
Exited with code 1
```

This appears to be happening right after I joined a private repository. I have _some_ suspicion this is a permissions issue/I'm getting a 3xx/4xx which has a [response](https://github.com/singer-io/tap-github/blob/master/tap_github.py#L388-L390) which is just a string.

## Notes

- reproduce-able in: https://circleci.com/gh/AlexanderMann/target-postgres/1156

## Suggested Musical Pairing

https://soundcloud.com/bibio/town-country?in=bibio/sets/a-mineral-love

**Comment by KAllan357** [comment]
Based on the context this indicates that the response from Github stored in the `comment` variable is not a JSON object and instead a string. Odd.

My first guess is that a quick debug would yield that Github is returning a permissions error or something not-helpful and that calling code higher up is not handling that appropriately. I also noticed that the line numbers in the stack trace are off from the code in master so I'm not sure what version this error popped up in.

**Comment by AlexanderMann** [comment]
@KAllan357 this was in 1.3.3. I just re-ran with 1.3.4 (didn't realize there was a new version as of 2 hours ago 😉). Upon re-running it _now_ passes...I'm not sure based on the diff with 1.3.3 what _would_ have changed which would have "fixed" this issue.

**Comment by AlexanderMann** [comment]
Passing: https://circleci.com/gh/AlexanderMann/target-postgres/1164
