### ISSUE TITLE
Error: 'str' object does not support item assignment line 363

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-github#54]
I'm seeing an intermittent error in my StitchData config:

`'str' object does not support item assignment`. It originates from line 363, which is this:

```diff
                'https://api.github.com/repos/{}/issues?state=all&sort=updated&direction=asc{}'.format(repo_path, query_string)
        ):
            issues = response.json()
            extraction_time = singer.utils.now()
            for issue in issues:
+                issue['_sdc_repository'] = repo_path
```

It appears that in some circumstances, issue is a string rather than a map. I'm unable to replicate an API call to see why this happens. It's possible that it's an error message or something?

My  recommendation would be to initially add some logging: if issue isn't a map then throw an error `'unexpected response format: ' + response`. Then at least we can see what's happening.

**Comment by sminnee** [comment]
Added a PR that should provide the aforementioned logging.

**Comment by luandy64** [comment]
@sminnee I'm curious to see what comes back in that response if you make the change you are suggesting. Have you done any investigation into what happens in the tap because of the 502?

**Comment by sminnee** [comment]
@luandy64 I'm hoping that you can merge and deploy #55 so we can see! It's not an error I've been able to replicate myself, I've only seen it on the StitchData server.

**Comment by sminnee** [comment]
Aha I didn't notice the 502. Presumably the github servers just get overloaded occassionally.

**Comment by sminnee** [comment]
Presumably #55 will provide a better error, but given that this is a 502 I don't think there will be much more that we can do here other than provide a better error message. So once #55 is merged we can close this.
