### ISSUE TITLE
issues: created_at and closed_at sent as strings

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-github#56]
The created_at and closed_at columns are sent as strings rather than datetimes. This leads to a suboptimal database.

**Comment by luandy64** [comment]
Which schemas are you referring to? And are you able to make a PR for this?

**Comment by luandy64** [comment]
Yup, just a JSON edit. It would look just like any of the other `date-time`s in the schema.

**Comment by sminnee** [comment]
Great thanks, PR raised. A brief search suggested that these 3 datetimes are the only ones lacking the metdata.
