### ISSUE TITLE
pr_commits not syncing

### ISSUE THREAD

**Issue by markthom-as** [singer-io/tap-github#78]
Hello, I noticed the other day that my `pr_commits` table had very incomplete data. Thinking this may have been an error with the integration, I set one up from scratch, syncing only `commits`, `pull_requests`, and `pr_commits`. 

In doing so, I realized that **pr_commits are no longer syncing**.

Is anyone else experiencing this issue?

**Comment by sbassin** [comment]
I recently added this table to an integration and noticed the same.

**Comment by vkruoso** [comment]
Im getting this error:
```
Partitioning by expressions of type FLOAT64 is not allowed at [3:53]
```

In the following tables:
```
issue_milestones
teams
issues_labels
events
team_members
```

Any ideias?

**Comment by NoLookForcePush** [comment]
I'm seeing this error as well

**Comment by vkruoso** [comment]
Is there anyone maintaining this repo? I can open a PR to get this solved if we have some guidance and the PR can actually be reviewed and merged.

**Comment by DevonPeroutky** [comment]
I'm pretty sure I have the fix to this issue (I have it working locally), but I am unable to push the branch up as describe in this issue: #80.

If that issue can be resolved, then I can quickly push up the fix for this issue.

**Comment by DevonPeroutky** [comment]
I just submitted this MASSIVE PR that I think will fix this: 

https://github.com/singer-io/tap-github/pull/81
